name: GamemodeUI
author: ItzLittleCute
main: ItzLittleCute\Main
api: 3.0.0
version: 1.0.0

commands:
 gameui:
  description: "GamemodeUI Command"
permission:
 gameui.cmd:
  description: "Permission For Open UI"